name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install
        run: npm i

      - name: Release
        run: npm run release-ci  -- --ci --no-git.requireCleanWorkingDir
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
